spring:
  data:
    mongodb:
      host: localhost
      database: petstore
  application:
    name: ps-store
server:
  servlet:
    context-path: /ps-store
  port: 10021
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

apps:
  pet:
    url:
      getById: http://ps-pet/pet/{petId}
